services:
  postgres:
    image: postgres:16-alpine
    container_name: portfolio-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: logan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: