spring:
  application:
    name: backend
  
  # Database Configuration (Connects to Docker or Neon)
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:portfolio_db}
    username: ${POSTGRES_USER:logan}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  # Automatically creates tables based on Java entities
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:kairnslogan@gmail.com}
    password: ${MAIL_PASSWORD:ycbc rrtb gnbb spqs}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Custom MinIO Configuration
minio:
  url: ${MINIO_URL:https://nixos-pi.tailf2f969.ts.net}
  bucket: ${MINIO_BUCKET:portfolio-assets}
  access-key: ${MINIO_ACCESS_KEY:QEUC9UU3V7JCDHN4SBU5}
  secret-key: ${MINIO_SECRET_KEY:tigOAY0iJU2S0TqHQDZAW80nDwu57SdV8G7hl2ad}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  admin:
    email: ${ADMIN_EMAIL:kairnslogan@gmail.com}